---
#output: github_document
output:
  github_document:
    toc: true
    toc_depth: 2
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## 1. First time R package installation

#### Package development prerequisites
If this is the first time you build and install an R package you can follow this [link](https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites),
which has simple installation instructions for Windows, Mac OSX and Linux.

To specifically install the command-line tools of Xcode for Mac OSX you might also need to run this line in terminal:  
``` bash
xcode-select --install
```


\  



## 2. Clang error on MacOS

### 2.1 issue 1
If you see this error on your MacOS:  
``` bash
clang: error: unsupported option ‘-fopenmp’
```

You can install another clang and point R to use that clang, which supports the -fopenmp paramter.
This solution was provided on [stackoverflow](https://stackoverflow.com/questions/43595457/alternate-compiler-for-installing-r-packages-clang-error-unsupported-option)

1. Install llvm on your mac
``` bash
brew install llvm
```

2. create a Makevars file
``` bash
touch ~/.R/Makevars
```

3. Add these lines to the Makevars file
```{bash, eval = FALSE}
# comment out first line 'CC= ... if there are errors with compiling a package
CC=/usr/local/opt/llvm/bin/clang -fopenmp
CXX=/usr/local/opt/llvm/bin/clang++

# Also potentially CXX11 (for C++11 compiler)
CXX11=/usr/local/opt/llvm/bin/clang++

# -O3 should be faster than -O2 (default) level optimisation ..
CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/opt/gettext/lib -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
CPPFLAGS=-I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include
```


### 2.2 issue 2

If you see this error on your MacOS, most likely with the latest macOS Mojave: 
```{bash, eval = FALSE}
Error message: 
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

solution: 
Installing the latest version of gofortran. 
https://github.com/fxcoudert/gfortran-for-macOS/releases/download/8.2/gfortran-8.2-Mojave.dmg
  
  
Reference: 
https://stackoverflow.com/questions/35999874/mac-os-x-r-error-ld-warning-directory-not-found-for-option
"I am having Mac OS Catalina and in my case installation of Homebrew, the newest gcc and Gfortran 8.2.0 solved the issue." -- Magda Orzechowska
"This worked for me in Mac OS Catalina as well! I used the gfortran 8.2 Mojave installation github.com/fxcoudert/gfortran-for-macOS/releases" -- Danny


## 3. 'Make' not found error

If you encounter this error:
```{bash, eval = FALSE}
Error in system(cmd) : (converted from warning) ‘make’ not found
```

Solution:  
Install the necessary [package development tools](https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites).





