# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

libNormFast <- function(raw_matrix, scalefactor) {
    .Call('_Giotto_libNormFast', PACKAGE = 'Giotto', raw_matrix, scalefactor)
}

logNormFast <- function(mymatrix) {
    .Call('_Giotto_logNormFast', PACKAGE = 'Giotto', mymatrix)
}

armaScaleRow <- function(Z) {
    .Call('_Giotto_armaScaleRow', PACKAGE = 'Giotto', Z)
}

armaScale <- function(Z) {
    .Call('_Giotto_armaScale', PACKAGE = 'Giotto', Z)
}

